# Generated by Django 5.1.4 on 2025-01-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_productos/'),
        ),
    ]
