# Generated by Django 5.1.4 on 2025-01-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0003_remove_cliente_factura_remove_cliente_foto_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='archivo',
            new_name='factura',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_archivo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
